# Generated by Django 5.2.6 on 2025-09-10 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0002_alter_inventario_insumo_alter_inventario_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insumo',
            name='precio',
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
