# Generated by Django 5.2.6 on 2025-09-18 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0004_promocion_promocionproducto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='stock_minimo',
        ),
        migrations.AddField(
            model_name='producto',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_minimo',
            field=models.IntegerField(default=0),
        ),
    ]
