# Generated by Django 5.2.6 on 2025-09-18 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0005_remove_inventario_stock_minimo_producto_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='unidad_medida',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
