# Generated by Django 5.2.6 on 2025-09-18 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0006_producto_unidad_medida'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='insumo',
            name='stock_minimo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='insumo',
            name='unidad_medida',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
