# Generated by Django 5.2.6 on 2025-09-24 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0009_item_producto_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Inventario.item'),
        ),
    ]
