# Generated by Django 5.2.6 on 2025-09-24 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0010_inventario_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='producto',
        ),
    ]
