# Generated by Django 5.2.6 on 2025-09-24 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0011_remove_inventario_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='stock_minimo',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='unidad_medida',
        ),
    ]
