# Generated by Django 5.2.6 on 2025-09-24 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0012_remove_producto_stock_minimo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
