# Generated by Django 5.2.6 on 2025-09-24 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0013_alter_item_cantidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='cantidad',
        ),
        migrations.AlterField(
            model_name='inventario',
            name='stock_actual',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
