# Generated by Django 5.2.6 on 2025-10-08 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0014_remove_item_cantidad_alter_inventario_stock_actual'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='eq_pollo',
            field=models.DecimalField(blank=True, choices=[(0.25, 'Cuarto'), (0.5, 'Medio'), (1.0, 'Entero')], decimal_places=2, max_digits=10, null=True),
        ),
    ]
