# Generated by Django 5.2.6 on 2025-09-11 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0003_remove_insumo_precio_producto_imagen'),
        ('venta', '0002_caja_cliente_metodopago_sesioncaja_venta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='sucursal',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Inventario.sucursal'),
        ),
    ]
