# Generated by Django 5.2.6 on 2025-09-11 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0004_tipoestado_alter_caja_sucursal_venta_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.tipoestado'),
        ),
    ]
