# Generated by Django 5.2.6 on 2025-09-22 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0006_caja_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caja',
            old_name='usuario',
            new_name='vendedor',
        ),
    ]
