# Generated by Django 5.2.6 on 2025-10-02 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0007_rename_usuario_caja_vendedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caja',
            name='vendedor',
        ),
        migrations.AddField(
            model_name='customuser',
            name='caja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='venta.caja'),
        ),
    ]
