# Generated by Django 5.2.6 on 2025-10-06 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0014_remove_item_cantidad_alter_inventario_stock_actual'),
        ('venta', '0008_remove_caja_vendedor_customuser_caja'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='promocion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Inventario.promocion'),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Inventario.producto'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='venta.tipoestado'),
        ),
    ]
