# Generated by Django 5.2.6 on 2025-10-13 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0010_alter_venta_metodo_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventa',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
